name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1,16 * *'

jobs:
  tests:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4, 8.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.3

      - name: Setup PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v1

      - name: Test
        run: vendor/bin/simple-phpunit -v

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.3

      - name: Setup PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: 8.0
          coverage: xdebug
          ini-values: xdebug.mode=coverage

      - name: Install dependencies
        uses: ramsey/composer-install@v1

      - name: Test with coverage
        run: vendor/bin/simple-phpunit -v --coverage-text --coverage-clover coverage.xml

      - name: Publish coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml

  composer-validate:
    name: Validate composer.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.3

      - name: Setup PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: 8.0
          coverage: none

      - name: Validate composer.json
        run: composer validate --strict --no-check-lock

  cs-check:
    name: PHP Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.3

      - name: Setup PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: 7.2
          coverage: none
          tools: php-cs-fixer

      - name: Check CS
        run: php-cs-fixer fix --dry-run --diff
